### PR TITLE
Fix for mangled URLs in MDX

### LINKED ISSUE #1465: tutorial converter mangles links
### Issue Description
See the first paragraph in the problem section of the Bayesian Structural Time Series tutorial (https://beanmachine.org/docs/overview/tutorials/Bayesian_Structural_Time_Series/BayesianStructuralTimeSeries/). This happens other places as well; see the reference section in https://beanmachine.org/docs/overview/tutorials/Robust_Linear_Regression/RobustLinearRegression/.

### PR DESCRIPTION
**Pull request by ndmlny-qs**
### Changes proposed
- Updates the `convert_ipynb_to_mdx` script to use `mdformat` for
  formatting markdown cells.
- Includes `mdformat` and `mdformat-myst` as required dev packages in
  `setup.py`.
- Resolves #1465 

### Types of changes
- [x] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/facebookresearch/beanmachine/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by horizon-blue** [comment]
@ndmlny-qs Sorry for the hassle. In this time the error is that we don't have `mdformat` internally, so our dependency checker throws an error. Let me try importing it and then try re-run the linter

**Comment by ndmlny-qs** [comment]
Thanks for letting me know. If `mdformat` is not available, and will not be available in the build process, I can find a different markdown formatter.

**Comment by ndmlny-qs** [comment]
@horizon-blue I am in favor of closing this PR as the code that fixes the mangled URLs is also in PR #1476. Do you have any objections?

**Comment by feynmanliang** [comment]
Let's keep this open? @horizon-blue has https://github.com/facebookresearch/beanmachine/pull/1476 stacked on top of this internally.

GH signals appear stale; this is green on internal CI

**Pull request closed without merging**
