### PR TITLE
Ot visual widget proposal

### PR DESCRIPTION
**Pull request by ndmlny-qs**
### Motivation
Adds widgets for diagnostics, for use in Jupyter notebooks.

### Changes proposed
Adding new user interactivity to model diagnostics.

### Test Plan
Tests forthcoming. This is already a big change.

### Types of changes
- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/facebookresearch/beanmachine/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by ndmlny-qs** [comment]
Looks like we will need to update the GH actions to include per-file ignores for flake8.

https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-per-file-ignores

I've added the `# flake8: noqa` flag  to ignore the modules with escape characters it does not have rules for.

**Comment by ndmlny-qs** [comment]
Looking at the GH actions, it looks like we are using `ufmt` to ensure black and usort have been run on the files for linting purposes. I've installed ufmt and run it on the files for this PR, and it shows not formatting errors. I also ran black and usort with no errors, so I'm not sure why the linting step is not passing.

**Comment by jpchen** [comment]
Thanks for doing this, looks like lint passes now :) I probably won't review the source code very closely, but give us some time this week to play around with it and lightly stress test it before merging.

**Comment by ndmlny-qs** [comment]
@jpchen Thanks for the fix. The code for the individual widgets all follow the pattern outlined below.

- compute the data needed for the widget
- transform the computed data into a Bokeh `ColumnDataSource`
- create figure(s)
- create glyphs
- create annotations
- create a help page for the widget
- modify the document the widget exists in and
  - bind data to the glyphs and glyphs to the figure(s)
  - bind annotations to the figure(s)
  - create widgets (buttons, lists etc)
  - create callbacks from the widgets to update the figure(s)
  - reset figures if needed
- show the widget

When you run the `Widgets.ipynb`, you will see how each one will render in the notebook. This is still just a proposal, which is why it is not in `src`. I look forward to the stress testing and further updating of the widgets

**Comment by ndmlny-qs** [comment]
This is one of the items I am going to close in favor of a new issue that encapsulates all the visual diagnostics tools in one place.

**Comment by feynmanliang** [comment]
SGTM

**Comment by ndmlny-qs** [comment]
closing in favor of a new issue outlining the tools

**Pull request closed without merging**
