### PR TITLE
Trace tool

### PR DESCRIPTION
**Pull request by ndmlny-qs**
### Motivation

Continued work on the diagnostics tool, this includes a model trace tool.

### Changes proposed

- Changes include new JavaScript and Python files for the Bokeh Application.
- Updates to helper modules in stats for the JavaScript

### Test Plan

The tool was run in the Coin flipping tutorial.

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/facebookresearch/beanmachine/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by ndmlny-qs** [comment]
@horizon-blue I am working on updating the notebook to mdx converter based on the revisions in this PR. I think this tool would be the first to merge as it directly updates (no change to prose) the coin flipping tutorial by adding it to the tutorial.

**Comment by horizon-blue** [comment]
:) sounds good. Internally I got Yarn and webpack successfully set up for #1691, though I can't merge my config yet because #1691 is still WIP. If we think this one will be merged sooner, then I will rebase my internal changes to this PR.

**Comment by ndmlny-qs** [comment]
@horizon-blue that's spectacular! I don't have a use case for PR #1691 yet, but do in this one which is why I suggested merging this first. But, I think if you can merge #1691 then I'll remove the [WIP] flag, and I can keep building from there.

**Comment by horizon-blue** [comment]
:) Finally merged #1691 after it pass the internal tests. However, it looks like we have to resolve quite a bit of merge conflicts before I can test out this PR.

Also, just as a FYI, I changed the diagnostic accessor a bit. It now [lazily imports the widgets only when necessary](https://github.com/facebookresearch/beanmachine/blob/main/src/beanmachine/ppl/diagnostics/tools/viz.py#L50-L53). That way we don't have to add Bokeh and IPython to our core dependencies.

**Comment by horizon-blue** [comment]
I took the liberty to resolve the merge conflicts with the marginal 1D tool so I can show both widgets in a single notebook. Hopefully I didn't break anything during the merge (the widget looks fine on my local jupyter session, though I still need to try it out to tell if it works in Bento.

**Comment by feynmanliang** [comment]
fbcode/beanmachine/beanmachine/ppl/diagnostics/tools/js/src/stats/histogram.ts
Warning
Line 1
LICENSELINT • missing-license
Hide Details
Open in VS Code @ FB
More info: https://fburl.com/fbsource-linters#license-lint

**Comment by horizon-blue** [comment]
Looks like we need to resolve the merge conflict on the Coin flipping tutorial again :). Can we also make sure that it's up-to-date? Looks like there're some changes in the trace plot widget that's not reflected in the tutorial.

**Comment by ndmlny-qs** [comment]
I rebased, fixed merge conflicts, and made sure coin flipping tutorial was the one already in the main branch. Let me know if there are any other problems I should address with this PR.

**Pull request closed without merging**
