### PR TITLE
Relocate test suite: `src/*/tests/` -> `tests/`

### PR DESCRIPTION
**Pull request by ntfrgl**
### Motivation
Currently, the Bean Machine test suite is aligned with and contained inside the library source tree, mostly residing in independent `src/*/tests/` subfolders. To allow for more code sharing and more structural flexibility in the test suite going forward, it is desirable to gather the tests into a dedicated top-level directory. This is in agreement with the default package structure in the official Python documentation [1], and with the Pytest recommendation to maintain tests "outside", rather than "as part of the application code", when a project has "many functional tests" [2].

[1] https://packaging.python.org/en/latest/tutorials/packaging-projects/
[2] https://docs.pytest.org/en/latest/explanation/goodpractices.html#choosing-a-test-layout-import-rules

### Changes proposed
As a first step, this PR moves most tests into the `tests/` directory. Currently excluded from this relocation are:
- `beanmachine/ppl/testlib` (utilities)
- `beanmachine/ppl/experimental/*/tests/*_test.py` (distinct library layer)
- `beanmachine/applications/*/tests/*_test.py` (distinct library layer)
- `beanmachine/graph/*/tests/*_test.cpp` (distinct test infrastructure)

The PR is structured into the following commits:
1. relocate Pytest suite
2. relocate GTest suite
3. revert (2) to simplify merging, but keep (2) for reference.

### Test Plan
The test coverage and results from `pytest` remain unchanged after the diff.

### Types of changes
- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/facebookresearch/beanmachine/blob/main/CONTRIBUTING.md)** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by horizon-blue** [comment]
Wow. I was under the impression that we were going to consolidate just the models being used in the test files, but this is a larger change than I initially anticipated :). I'm personally in favor of this change, though I'll also check with the team to see if people have any concern about this.

This is likely going to break our internal test suite since we need to update our test config internally as well. Let me import it first and see what changes are necessary.

**Comment by ntfrgl** [comment]
Thank you for looking into it! My main motivation here is to take a first step towards disentangling the test suite structure from the backend implementation structure.

As far as the open source view on the source tree goes, the only required change to detect the tests was to move from `pytest src` to `pytest .` or `pytest src tests`, i.e., updating the search path for tests assuming a suitable import strategy.

I'm surprised, though, that not even the following unmoved test were not found - unless they were disabled in the specific test configuration you ran.
- `beanmachine/ppl/experimental/*/tests/*_test.py`
- `beanmachine/applications/*/tests/*_test.py`

**Comment by horizon-blue** [comment]
> I'm surprised, though, that not even the following unmoved test were not found 

:) Ah, this this because our internal test runner only runs test suites that include the files being changed, so in this case, our test suite was not being run since the files are no longer part of it.

**Comment by horizon-blue** [comment]
:) Okay, so I checked with the team, and none of them is against this move. I had to modify a few files and update our internal config files on top of this PR, though, in order to get everything connected. I will export my changes shortly -- this might create a forced push on this branch, but we should still be able to see the commit history from this PR.

**Comment by horizon-blue** [comment]
Oh wait, it looks like I can't export the changes here because the pull request is coming from a forked repo rather than a branch. I should still be able to merge the my changes in without syncing them into this PR. They are quite small, so the CI should still pass.

For references, here're a two things that I changed
- Moved experimental tests to the new directory as well, because internally they are under the same test suite as the rest of the `ppl/` tests and it is be easier to move all of them together. The application tests were not touched because they are under a different test suite.
- Moved `src/beanmachine/ppl/conftest.py` to `tests/ppl/conftest.py`

**Pull request closed without merging**
